@startuml

class Autor {
	-int id
	-string uuid
	-LocalDateTime createdAt
	-string nome
	-string email
	-string descricao
}

class Categoria {
	-int id
	-string uuid
	-LocalDateTime createdAt
	-string nome
}

class Livro {
	-int id
	-string uuid
	-LocalDateTime createdAt
	-string titulo
	-string resumo
	-string sumario
	-double preco
	-string isbn
	-int numeroPaginas
	-LocalDateTime dataPublicacao
}

Livro *-- Categoria
Livro *-- Autor

@enduml
